# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf52217f3a0125c0e579699807dbd9e9"
name = "Upsell Conversion Booster"
application_url = "https://scholar-menu-birds-dat.trycloudflare.com"
embedded = true
handle = "upsell-conversion-booster"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_themes,write_products"

[auth]
redirect_urls = [
  "https://scholar-menu-birds-dat.trycloudflare.com/auth/callback",
  "https://scholar-menu-birds-dat.trycloudflare.com/auth/shopify/callback",
  "https://scholar-menu-birds-dat.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
