# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ads-sidebar-app-new"
client_id = "840adb02451fa7b8e307784a1aff5e1a"
application_url = "https://stone-dressing-determining-robbie.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://stone-dressing-determining-robbie.trycloudflare.com/auth/callback",
  "https://stone-dressing-determining-robbie.trycloudflare.com/auth/shopify/callback",
  "https://stone-dressing-determining-robbie.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devteammase.myshopify.com"
