# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf52217f3a0125c0e579699807dbd9e9"
name = "Upsell Conversion Booster"
handle = "upsell-conversion-booster"
application_url = "https://awareness-headers-monitor-effect.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://awareness-headers-monitor-effect.trycloudflare.com/auth/callback",
  "https://awareness-headers-monitor-effect.trycloudflare.com/auth/shopify/callback",
  "https://awareness-headers-monitor-effect.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
